const prefix = "USER_CREDENTIALS_STATE_";

export const SETUP_CREDENTIAL_USERNAME = prefix + "SETUP_CREDENTIAL_USERNAME";
export const SETUP_CREDENTIAL_PASSWORD = prefix + "SETUP_CREDENTIAL_PASSWORD";
export const SETUP_CREDENTIAL_EMAIL = prefix + "SETUP_CREDENTIAL_EMAIL";

export const RESET_CREDENTIALS = prefix + "RESET_CREDENTIALS";