const prefix = "USER_STATE_";


export const USER_AUTHENTIFICATED_ACTION = prefix + "USER_AUTHENTIFICATION_ACTION";
export const SETUP_TOKEN_FROM_LOCAL_STORAGE = prefix + "SETUP_TOKEN_FROM_LOCAL_STORAGE";
export const USER_LOGOUT_ACTION = prefix + "USER_LOGOUT_ACTION";